- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendFragment.kt
관련 이슈
- closed #29 
작업 사진/동영상 (선택)
- 업더요
작업한 내용
- 메모리릭 방지 위한 adapter 수정
PR 포인트
- 메모리릭 방지 위한 adapter 수정
> #29 [fix] 전체뷰/ 메모리릭 방지 위한 adapter 수정

- app/src/main/java/com/sopt/peekabookaos/data/entity/BaseResponse.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/CreateUpdateRepository.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/CreateUpdateRepositoryImpl.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/DetailRepository.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/DetailRepositoryImpl.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/NotificationRepository.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/NotificationRepositoryImpl.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/RecommendRepository.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/RecommendRepositoryImpl.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/SearchRepository.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/SearchRepositoryImpl.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepository.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepositoryImpl.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/CreateUpdateService.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/DetailService.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/NotificationService.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/RecommendService.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/SearchService.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/ShelfService.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/UpdateCreateService.kt
- app/src/main/java/com/sopt/peekabookaos/data/source/remote/CreateUpdateDataSource.kt
- app/src/main/java/com/sopt/peekabookaos/data/source/remote/DetailDataSource.kt
- app/src/main/java/com/sopt/peekabookaos/data/source/remote/NotificationDataSource.kt
- app/src/main/java/com/sopt/peekabookaos/data/source/remote/RecommendDataSource.kt
- app/src/main/java/com/sopt/peekabookaos/data/source/remote/SearchDataSource.kt
- app/src/main/java/com/sopt/peekabookaos/data/source/remote/ShelfDataSource.kt
- app/src/main/java/com/sopt/peekabookaos/di/RetrofitServiceModule.kt
관련 이슈
- closed #14
작업 사진/동영상 (선택)
- x
작업한 내용
- 서비스, 데이터소스, 레포지토리, 레포지토리impl
PR 포인트
- 없습니다
> #14 [setting] 서버 세팅

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
- app/src/main/res/layout/activity_detail.xml
관련 이슈
- closed #38 
작업 사진/동영상 (선택)
-
위에는 더미값으로 내 책장을 넣은 것
밑에는 더미값으로 친구 책장을 넣은 것
작업한 내용
- 상세뷰/ 내 책장, 친구 책장 뷰 수정
- ic_edit, ic_delete -> visiblity처리
- tag 이용한 getIntExtra로 넘겨 받는 값에 따라 다른 데이터 띄우기
PR 포인트
- tag 이용한 getIntExtra
> #38 [fix] 상세뷰/ 내 책장, 친구 책장 뷰 수정

- app/src/main/java/com/sopt/peekabookaos/data/entity/BaseResponse.kt
- app/src/main/java/com/sopt/peekabookaos/data/entity/User.kt
- app/src/main/java/com/sopt/peekabookaos/data/entity/response/SearchUserResponse.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/SearchRepository.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/SearchRepositoryImpl.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/SearchService.kt
- app/src/main/java/com/sopt/peekabookaos/data/source/remote/SearchDataSource.kt
- app/src/main/java/com/sopt/peekabookaos/di/RepositoryModule.kt
- app/src/main/java/com/sopt/peekabookaos/di/RetrofitModule.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/search/user/SearchUserActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/search/user/SearchUserViewModel.kt
- app/src/main/java/com/sopt/peekabookaos/util/extensions/UiState.kt
관련 이슈
- closed #42 
작업 사진/동영상 (선택)
-
작업한 내용
- 사용자검색 서버 구현
PR 포인트
- NPE 수정중
> #42 [feat] 사용자검색 / 서버 구현

- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyActivity.kt
- app/src/main/res/layout/fragment_bookshelf.xml
관련 이슈
- closed #45
작업 사진/동영상 (선택)
-
https://user-images.githubusercontent.com/91793891/211493767-af71f57d-4bcb-4481-8aec-a42b9b8f3614.mp4
작업한 내용
- 클릭리스너, 인텐트
PR 포인트
- 클릭리스너, 인텐트
> #45 [add] bookshelf,pick,notification /clickListenter, Intent 추가

- app/src/main/java/com/sopt/peekabookaos/data/entity/Book.kt
- app/src/main/java/com/sopt/peekabookaos/data/entity/Books.kt
- app/src/main/java/com/sopt/peekabookaos/data/entity/FriendList.kt
- app/src/main/java/com/sopt/peekabookaos/data/entity/Pick.kt
- app/src/main/java/com/sopt/peekabookaos/data/entity/PickModify.kt
- app/src/main/java/com/sopt/peekabookaos/data/entity/Picks.kt
- app/src/main/java/com/sopt/peekabookaos/data/entity/SelfIntro.kt
- app/src/main/java/com/sopt/peekabookaos/data/entity/Shelf.kt
- app/src/main/java/com/sopt/peekabookaos/data/entity/response/MyShelfResponse.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepository.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepositoryImpl.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/ShelfService.kt
- app/src/main/java/com/sopt/peekabookaos/data/source/remote/ShelfDataSource.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfFriendAdapter.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfPickAdapter.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfShelfAdapter.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
- app/src/main/res/layout/fragment_bookshelf.xml
- app/src/main/res/layout/item_bookshelf_pick.xml
- app/src/main/res/layout/item_bookshelf_shelf.xml
- app/src/main/res/layout/item_bookshelf_user_profile.xml
- app/src/main/res/values/strings.xml
관련 이슈
- closed #49
작업 사진/동영상 (선택)
-kotlin.runCatching { shelfDataSource.getMyShelf() }.map { response ->
response.data!!
작업한 내용
- Myshelf 서버 연결
PR 포인트
-  Myshelf 서버 연결
> #49 [feat] 내 책장 서버 구현/ 서버구현

- app/src/main/java/com/sopt/peekabookaos/data/entity/Notification.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/NotificationRepository.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/NotificationRepositoryImpl.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/NotificationService.kt
- app/src/main/java/com/sopt/peekabookaos/data/source/remote/NotificationDataSource.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationViewModel.kt
- app/src/main/res/layout/item_notification.xml
관련 이슈
- closed #58
작업 사진/동영상 (선택)
- 
작업한 내용
- 알림 서버 구현
PR 포인트
- 알림 서버 구현
> #58 [feat] 알림 서버 구현/ 서버구현

- app/src/main/java/com/sopt/peekabookaos/data/entity/response/FollowResponse.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/SearchRepository.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/SearchRepositoryImpl.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/SearchService.kt
- app/src/main/java/com/sopt/peekabookaos/data/source/remote/SearchDataSource.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/search/user/SearchUserViewModel.kt
관련 이슈
- closed #53
작업 사진/동영상 (선택)
-
작업한 내용
- 팔로우,언팔로우 서버 통신 구현
PR 포인트
- 없습니다
> #53 [feat] 사용자 검색 / 팔로우,언팔로우 서버 통신 구현

- app/src/main/java/com/sopt/peekabookaos/data/entity/request/PickRequest.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepository.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/ShelfRepositoryImpl.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/NotificationService.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/ShelfService.kt
- app/src/main/java/com/sopt/peekabookaos/data/source/remote/ShelfDataSource.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/pickModify/PickModifyViewModel.kt
관련 이슈
- closed #65
작업 사진/동영상 (선택)
-
https://user-images.githubusercontent.com/91793891/211777801-2b4d272d-df75-4a88-82d5-cca5bf08aea1.mp4
작업한 내용
- pick수정 서버 연결
PR 포인트
- pick수정 서버 연결
> #65 [feat] pick수정/ pick수정 서버 연결

- app/src/main/java/com/sopt/peekabookaos/di/RetrofitModule.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
- app/src/main/res/layout/fragment_bookshelf.xml
관련 이슈
- closed #76
작업 사진/동영상 (선택)
-
https://user-images.githubusercontent.com/91793891/211886572-e973312f-7b6b-4f0c-beef-9ea65ec6a6bb.mp4
작업한 내용
- databinding > viewbinding 으로 변경
PR 포인트
- databinding > viewbinding 으로 변경
> #76[fix] bookshelf / databinding > viewbinding 으로 변경

- app/src/main/java/com/sopt/peekabookaos/di/RetrofitModule.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
관련 이슈
- closed #74
작업 사진/동영상 (선택)
-
작업한 내용
-  Intent 수정- LOCATION 넘겨주기, Header 추가
PR 포인트
-  Intent 수정- LOCATION 넘겨주기, Header 추가
> #74[feat] bookshelf / Intent 수정- LOCATION 넘겨주기, Header 추가

- app/src/main/java/com/sopt/peekabookaos/data/entity/NaverBookItem.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/NaverRepository.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/NaverRepositoryImpl.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeScannerActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeViewModel.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookViewModel.kt
- app/src/main/res/layout/item_recommend.xml
관련 이슈
- closed #87
작업 사진/동영상 (선택)
- x
작업한 내용
- 바코드 분기처리 수정
PR 포인트
- 없습니다.
> #87 [fix] 바코드 분기처리 수정

- app/src/main/java/com/sopt/peekabookaos/data/entity/Picks.kt
- app/src/main/java/com/sopt/peekabookaos/data/entity/response/CreateBookResponse.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/CreateUpdateService.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/DetailService.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/createUpdateBook/CreateUpdateBookViewModel.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationActivity.kt
- app/src/main/res/layout/fragment_bookshelf.xml
관련 이슈
- closed #93
작업 사진/동영상 (선택)
-
작업한 내용
- design qa 반영, 서버 변동 반영 (response, request 수정)
PR 포인트
- design qa 반영, 서버 변동 반영 (response, request 수정)
> #93[fix] design qa 반영, 서버 변동 반영

- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfPickDecoration.kt
- app/src/main/res/layout/fragment_bookshelf.xml
- app/src/main/res/layout/item_bookshelf_pick.xml
- app/src/main/res/values/strings.xml
관련 이슈
- closed #95
작업 사진/동영상 (선택)
-
작업한 내용
- bookshelf recyclerview 간격 조정, empty view 적용
PR 포인트
- bookshelf recyclerview 간격 조정, empty view 적용
> #95 [fix] 디자인 qa 적용

- app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookViewModel.kt
관련 이슈
- closed #103 
작업 사진/동영상 (선택)
- x
작업한 내용
- 코드로
PR 포인트
- 말해요
> #103 [fix] 스택 및 stateflow 수정

- app/src/main/java/com/sopt/peekabookaos/data/repository/DetailRepositoryImpl.kt
- app/src/main/java/com/sopt/peekabookaos/domain/repository/DetailRepository.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailViewModel.kt
관련 이슈
- closed #129 
작업 사진/동영상 (선택)
-
작업한 내용
- 도메인에서 NoResponse쓰이는 것 수정
PR 포인트
- 반환형을 NoResponse에서 Boolean으로 수정했습니다 
+ 아직 상세뷰에서 사진 안뜨는 오류 수정 못했는데 책장에 책이 안떠서..! 일단 수정한 부분 먼저 피알 날려놓습니다
> #129 [refactor] 상세뷰 수정

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/sopt/peekabookaos/presentation/login/LoginActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/socialLogin/SocialLoginFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/socialLogin/SocialLoginViewModel.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputFragment.kt
- app/src/main/java/com/sopt/peekabookaos/util/KakaoLoginCallback.kt
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/layout/fragment_social_login.xml
- app/src/main/res/layout/fragment_user_input.xml
- app/src/main/res/navigation/nav_login.xml
- app/src/main/res/values/strings.xml
관련 이슈
- closed #150
작업사진/동영상 (선택)
https://user-images.githubusercontent.com/84129098/228606744-3ff53851-8578-4325-a1b8-262b844d2079.mov
작업한 내용
- 로그인 액티비티 생성
- 로그인 네비게이션 구현
- 소셜로그인 프래그먼트, 회원정보입력 프래그먼트 생성
- 각각 프래그먼트에 백버튼 구현
PR 포인트
- ㅠ3ㅠ
> #150 [refactor] 로그인 네비게이션 구현

- app/src/main/java/com/sopt/peekabookaos/data/entity/response/LoginResponse.kt
- app/src/main/java/com/sopt/peekabookaos/data/entity/response/RefreshResponse.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/RefreshRepositoryImpl.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/RefreshService.kt
- app/src/main/java/com/sopt/peekabookaos/data/source/remote/RefreshDataSource.kt
- app/src/main/java/com/sopt/peekabookaos/di/RefreshRetrofitModule.kt
- app/src/main/java/com/sopt/peekabookaos/di/RepositoryModule.kt
- app/src/main/java/com/sopt/peekabookaos/di/RetrofitModule.kt
- app/src/main/java/com/sopt/peekabookaos/di/RetrofitServiceModule.kt
- app/src/main/java/com/sopt/peekabookaos/domain/entity/Token.kt
- app/src/main/java/com/sopt/peekabookaos/domain/repository/AuthRepository.kt
- app/src/main/java/com/sopt/peekabookaos/domain/repository/RefreshRepository.kt
- app/src/main/res/values/strings.xml
관련 이슈
- closed #164
작업 사진/동영상 (선택)
- x
작업한 내용
- 리프래쉬 레트로핏 모듈 생성
- 리프래쉬 서버 구현
PR 포인트
- 없습니다..
> #164 [feat] 리프래쉬 api 구현

- app/src/main/java/com/sopt/peekabookaos/data/entity/response/SearchUserResponse.kt
- app/src/main/java/com/sopt/peekabookaos/data/repository/BlockRepositoryImpl.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/BlockService.kt
- app/src/main/java/com/sopt/peekabookaos/data/source/remote/BlockDataSource.kt
- app/src/main/java/com/sopt/peekabookaos/di/RepositoryModule.kt
- app/src/main/java/com/sopt/peekabookaos/di/RetrofitServiceModule.kt
- app/src/main/java/com/sopt/peekabookaos/domain/entity/User.kt
- app/src/main/java/com/sopt/peekabookaos/domain/repository/BlockRepository.kt
- app/src/main/java/com/sopt/peekabookaos/domain/usecase/DeleteBlockUseCase.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/search/user/SearchUserViewModel.kt
- app/src/main/java/com/sopt/peekabookaos/util/binding/BindingAdapter.kt
- app/src/main/res/drawable/shape_g2_line_circle.xml
- app/src/main/res/layout/activity_search_user.xml
- app/src/main/res/values/strings.xml
관련 이슈
- closed #154 
작업 사진/동영상 (선택)
https://user-images.githubusercontent.com/84129098/230552427-68b2ea41-8566-4427-a479-aa6306057813.mov
작업한 내용
- 차단해제 서버 구현
- 바인딩어댑터로 버튼 상태 구현
PR 포인트
- 바인딩어댑터..?
- 차단해제 서버 `DeleteBlockUseCase` 가져다 쓰기
> #154 [ui/feat] 사용자 검색 뷰에 차단해제 구현

- app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageViewModel.kt
- app/src/main/res/layout/fragment_my_page.xml
- app/src/main/res/values/strings.xml
관련 이슈
- closed #159 
작업 사진/동영상 (선택)
- x
작업한 내용
- margin값, 텍스트 스타일 수정
- 스트링값 수정
PR 포인트
-
> #159 [fix] 마이페이지 수정

- app/src/main/java/com/sopt/peekabookaos/data/repository/AuthRepositoryImpl.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/AuthService.kt
- app/src/main/java/com/sopt/peekabookaos/data/source/remote/AuthDataSource.kt
- app/src/main/java/com/sopt/peekabookaos/domain/repository/AuthRepository.kt
- app/src/main/java/com/sopt/peekabookaos/domain/usecase/DeleteUserUseCase.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/withdraw/WithdrawViewModel.kt
관련 이슈
- closed #171 
작업 사진/동영상 (선택)
- x
작업한 내용
- 탈퇴하기 api 구현
PR 포인트
- 온보딩 구현하고 온보딩 state 넣을게요
> #171 [feat] 탈퇴하기 api 구현

- app/src/main/java/com/sopt/peekabookaos/data/repository/RefreshRepositoryImpl.kt
- app/src/main/java/com/sopt/peekabookaos/data/service/RefreshService.kt
- app/src/main/java/com/sopt/peekabookaos/data/source/remote/RefreshDataSource.kt
- app/src/main/java/com/sopt/peekabookaos/di/RefreshRetrofitModule.kt
- app/src/main/java/com/sopt/peekabookaos/di/RetrofitModule.kt
- app/src/main/java/com/sopt/peekabookaos/domain/repository/RefreshRepository.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeScannerFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeViewModel.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/main/MainActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/main/MainViewModel.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/myPage/LogoutDialog.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageViewModel.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/socialLogin/SocialLoginFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputViewModel.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/withdraw/WithdrawDialog.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/dialog_logout.xml
- app/src/main/res/values/strings.xml
관련 이슈
- closed #177 
작업 사진/동영상 (선택)
https://user-images.githubusercontent.com/84129098/230757603-d62f6eea-06b2-4ffd-b4fc-cbea4bfd99af.mov
작업한 내용
- 로그아웃 다이얼로그 구현
- 로그아웃 시 로컬db 초기화
- 뷰 상태관리
- 바코드 카메라 권한 로직 수정
- 리프래시api 로직 수정
PR 포인트
- 딱히 없습니다
> #177 [ui/feat/fix] 로그아웃 구현, 뷰 상태/스택관리, 바코드 카메라 권한 로직 수정, 리프래시api 로직 수정

- app/src/main/java/com/sopt/peekabookaos/presentation/block/BlockedUserActivity.kt
- app/src/main/res/layout/activity_blocked_user.xml
- app/src/main/res/values/strings.xml
관련 이슈
- closed #195 
작업 사진/동영상 (선택)
-
작업한 내용
- 사용자 차단리스트 엠티뷰
PR 포인트
- 사용자 차단리스트 엠티뷰
> #195 [fix] 사용자 차단리스트 수정

- app/src/main/res/layout/item_notification.xml
- app/src/main/res/values/strings.xml
관련 이슈
- closed #197 
작업 사진/동영상 (선택)
-
작업한 내용
- QA 반영(회원 정보 입력, 팔로우 시 뜨는 알림 item 제약 수정)
PR 포인트
- 없습니다!
> #197 [chore] 회원 정보 입력, 팔로우 시 뜨는 알림 item 제약 수정

- app/src/main/java/com/sopt/peekabookaos/presentation/createBook/CreateBookFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/detail/DetailActivity.kt
- app/src/main/res/layout/dialog_warning.xml
관련 이슈
- closed #210 
작업 사진/동영상 (선택)
- x
작업한 내용
- 책등록에서 책상세보기로 LOCATION 보내기
- 책삭제 팝업 간격 조정
PR 포인트
- 없습니다~
> #210 [QA] 책등록에서 책상세보기로 LOCATION 보내기, 책삭제 팝업 간격 조정

- app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputFragment.kt
- app/src/main/res/layout/fragment_bookshelf.xml
관련 이슈
- closed #214 
작업 사진/동영상 (선택)
- 없습니다~
작업한 내용
-userInput 프로필 터치 영역 +가 아닌 프로필 자체도 터치 영역 확장
-bookshelf 친구 empty view 위치 조정
PR 포인트
- 없습니다!
> #214 [QA] userInput 프로필 터치 영역 확대 / bookshelf 친구 empty view 위치 조정

- app/src/main/res/values-hdpi/dimen.xml
- app/src/main/res/values-mdpi/dimen.xml
- app/src/main/res/values-xhdpi/dimen.xml
- app/src/main/res/values-xxhdpi/dimen.xml
- app/src/main/res/values-xxxhdpi/dimen.xml
관련 이슈
- closed #216 
작업 사진/동영상 (선택)
-
작업한 내용
- dpi관계 없이 높이 고정
PR 포인트
-없습니닷
> #216 [qa] bookshelf bottomsheet 높이 조정

- app/src/main/java/com/sopt/peekabookaos/di/RetrofitModule.kt
관련 이슈
- closed #222 
작업 사진/동영상 (선택)
- x
작업한 내용
- 갱신 400 처리
PR 포인트
- 갱신 400 처리
> #222 [QA] 리프래시 api 400일 때 자동로그인 해제 로직 구현

- app/src/main/res/layout/item_search_book.xml
관련 이슈
- closed #225 
작업 사진/동영상 (선택)
작업한 내용
- 책검색뷰 작가명 제약 수정
PR 포인트
- 없숨다
> #225 [QA] 책검색뷰 작가명 제약 수정

- app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputViewModel.kt
관련 이슈
- closed #230 
작업 사진/동영상 (선택)
- (생략)
작업한 내용
- 천지인 아래아도 정규식에 포함
- 문자를 전부 다 지웠을 때, 토스트 메세지 뜨는 것 수정
PR 포인트
- 독특한 상황들이니 어디가 바뀌었는지 한 번씩 봐보셔요~
> #230 [qa] user input 정규식 수정

- app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyViewModel.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputViewModel.kt
관련 이슈
- closed #232 
작업 사진/동영상 (선택)
-
중복확인 체크메세지 로직 수정 (회원가입뷰)
https://github.com/team-peekabook/Peekabook-AOS/assets/101049601/6be5e18f-de01-455f-9129-20a421422534
정규표현식 수정 
https://github.com/team-peekabook/Peekabook-AOS/assets/101049601/e6dfd408-7aa7-498f-b39a-1c3fbbc4eb6c
https://github.com/team-peekabook/Peekabook-AOS/assets/101049601/0cccabf6-808a-48f1-b52b-1e98bce537ab
작업한 내용
- 정규표현식 수정 (회원가입뷰/프로필 수정뷰)
- 중복확인 체크메세지 로직 수정 (회원가입뷰)
PR 포인트
- 정규표현식 수정 (회원가입뷰/프로필 수정뷰)
- 중복확인 체크메세지 로직 수정 (회원가입뷰)
> #232 [QA] 정규표현식 수정, 중복확인 체크메세지 로직 수정

- app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyViewModel.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputViewModel.kt
관련 이슈
- closed #234 
- closed #235
작업 사진/동영상 (선택)
-
https://github.com/team-peekabook/Peekabook-AOS/assets/101049601/5e1265fe-f858-458a-8a78-54b7ba3c9ab4
https://github.com/team-peekabook/Peekabook-AOS/assets/101049601/578657ef-0cf8-4463-8c57-c5508985829d
작업한 내용
- 회원가입뷰 프로필 수정뷰 닉네임 길이 제한 수정 
PR 포인트
- 회원가입뷰 프로필 수정뷰 닉네임 길이 6글자 제한 수정
> [QA] 회원가입뷰 프로필 수정뷰 닉네임 길이 제한 수정 

- app/src/main/java/com/sopt/peekabookaos/presentation/report/ReportActivity.kt
- app/src/main/res/layout/activity_profile_modify.xml
관련 이슈
- closed #238 
작업 사진/동영상 (선택)
- 기차라.. 찍을 수 없었어요 그러나 확인했습니다
작업한 내용
- 프로필 수정뷰 추가버튼 위치 수정, 신고하기뷰 뒤로가기 버튼 클릭가능 여부 수정
PR 포인트
- 프로필 수정뷰 추가버튼 위치 수정, 신고하기뷰 뒤로가기 버튼 클릭가능 여부 수정
> [QA] #238 프로필 수정뷰 추가버튼 위치 수정, 신고하기뷰 뒤로가기 버튼 클릭가능 여부 수정

- app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeGuideView.kt
관련 이슈
- closed #243
작업 사진/동영상 (선택)
-
작업한 내용
- 바코드 검색뷰 안내메세지 중앙정렬
PR 포인트
- 없습니다
> #243 [feat] 바코드 검색뷰 안내메세지 중앙정렬

- app/src/main/java/com/sopt/peekabookaos/PeekabookApplication.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/networkError/NetworkErrorActivity.kt
관련 이슈
- closed #236
작업 사진/동영상 (선택)
https://github.com/team-peekabook/Peekabook-AOS/assets/84129098/90eaaa28-bceb-4e66-be34-1fb2b1cb0b8b
작업한 내용
- 뒤로가기 연타 로직 추가
PR 포인트
- 없습니당
> #236 [fix] 뒤로가기 연타 로직 추가

- app/src/main/java/com/sopt/peekabookaos/di/RefreshRetrofitModule.kt
- app/src/main/java/com/sopt/peekabookaos/di/RetrofitModule.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookShelfViewModel.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/bookshelf/BookshelfFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/main/MainViewModel.kt
관련 이슈
- closed #246
작업 사진/동영상 (선택)
https://github.com/team-peekabook/Peekabook-AOS/assets/84129098/84a9357c-373e-4989-9578-52dda95c5a2f
작업한 내용
- bookshelf 뷰모델에서 onFailure에서 불필요하게 변경되는 값 제거했습니다
PR 포인트
- 혹시 .. 꼭 필요한 코드인가요? @stellar-halo
> #246 [fix] 자동로그인 만료 후 기존 Api 무한호출되는 버그 수정

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyViewModel.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/report/ReportActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputFragment.kt
- app/src/main/res/drawable/shape_white66fill_redline_0_rect.xml
- app/src/main/res/drawable/shape_white88fill_redline_0_rect.xml
- app/src/main/res/layout/activity_report.xml
- app/src/main/res/layout/fragment_user_input.xml
관련 이슈
- closed #255
작업 사진/동영상 (선택)
-
작업한 내용
- 
PR 포인트
-
> #255 [QA] 신고하기 글자수 제한

- app/src/main/java/com/sopt/peekabookaos/data/entity/RecommendEntity.kt
관련 이슈
- closed #257 
작업 사진/동영상 (선택)
-
작업한 내용
- 친구프로필 이미지 nullable하게 수정
PR 포인트
- ?를 주목해주세요
> #257 [hotfix] RecommendEntity의friendImage nullable 처리

- app/src/main/res/layout/item_notification.xml
관련 이슈
- closed #260 
작업 사진/동영상 (선택)
-
수정 전
수정 후
작업한 내용
- v_notification_book_title margin을 mention과 동일하게수정
PR 포인트
- 없습니다 @+ ㅎㅎ
> #260 [ui] tv_notification_book_title margin 수정(mention과 동일 margin)

- .github/workflows/pr_checker.yml
- app/build.gradle
- build.gradle
관련 이슈
- closed #266
작업 사진/동영상 (선택)
- x
작업한 내용
- 파이어베이스 gradle 추가
PR 포인트
- x
> #266 [chore] 파이어베이스 gradle 추가 및 yml 수정

- .idea/kotlinc.xml
- app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/profileModify/ProfileModifyBottomSheetFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputBottomSheetFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/userInput/UserInputFragment.kt
- app/src/main/res/layout/dialog_profile_bottom_sheet.xml
관련 이슈
- closed #265
작업 사진/동영상 (선택)
-
작업한 내용
-  userInput/profileModify camera bottomsheet xml 삭제 및 로직 삭제
PR 포인트
- 없습니다!
> #265 [fix] 회원정보입력/프로필수정 camera bottomsheet 제거

- app/src/main/res/layout/activity_detail.xml
관련 이슈
- closed #269
작업 사진/동영상 (선택)
https://github.com/team-peekabook/Peekabook-AOS/assets/84129098/94cf2e96-4899-46dd-8249-669c5f5cce9e
작업한 내용
- 메모 visible 처리
- 작가 정렬 수정
PR 포인트
- 없습니다
> #269 [ui] 책상세보기뷰 메모 visible 처리

- app/src/main/res/values/strings.xml
관련 이슈
- closed #271
작업 사진/동영상 (선택)
- x
작업한 내용
- 앱 이름 수정 (PEEKABOOK -> 피카북)
PR 포인트
- 없습니다
> #271 [chore] 앱 이름 수정

- .github/workflows/pr_checker.yml
관련 이슈
- closed #286
작업 사진/동영상 (선택)
-
작업한 내용
- cd 추가
PR 포인트
- 제발 돼라
> #286 [chore] apk 업로드 CD 구현

- app/src/main/java/com/sopt/peekabookaos/di/NaverRetrofitModule.kt
- app/src/main/java/com/sopt/peekabookaos/di/RefreshRetrofitModule.kt
- app/src/main/java/com/sopt/peekabookaos/di/RetrofitModule.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/barcodeScanner/BarcodeScannerFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/book/BookActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/search/book/SearchBookFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/splash/SplashViewModel.kt
- app/src/main/res/navigation/nav_book.xml
관련 이슈
- closed #284
작업 사진/동영상 (선택)
https://github.com/team-peekabook/Peekabook-AOS/assets/84129098/40e1f998-6e0a-4c7b-b3da-5c0bc4b128c5
작업한 내용
- book 네비게이션 startDestination barcodeScannerFragment에서 searchBookFragment로 수정
- searchBookFragment에서 뒤로가기 버튼 누를 시 액티비티 종료하는 로직 추가
PR 포인트
- 이걸 왜 이제서야 발견했을까...
> #284 [fix] 친구책장뷰 / 책추천하기 버튼 클릭시 카메라 권한 토스트 뜨는 버그 개선

- .github/workflows/pr_checker.yml
- app/build.gradle
관련 이슈
- closed #290 
작업 사진/동영상 (선택)
- x
작업한 내용
- build variants를 debug/release로 설정했을 때 각각 서버 주소 바꿔서 빌드되게 해놨습니다
PR 포인트
- 로컬프로퍼티 업데이트해주세요
> #290 [build] dev, prod 서버 분리

- app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageViewModel.kt
- app/src/main/res/layout/fragment_my_page.xml
관련 이슈
- closed #292
작업 사진/동영상 (선택)
-
작업한 내용
- 
PR 포인트
-
> #292 [ui] 마이페이지 제약 및 마진값 수정

- app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendAdapter.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendedFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendingFragment.kt
관련 이슈
- closed #306
작업 사진/동영상 (선택)
-
작업한 내용
- 
PR 포인트
-
> #306 [refactor] 책추천 어댑터 변수명 수정

- app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendViewModel.kt
관련 이슈
- closed #308
작업 사진/동영상 (선택)
-
작업한 내용
- 
PR 포인트
-
> #308 [refactor] RecommendViewModel nullable 수정

- app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendViewModel.kt
관련 이슈
- closed #312
작업 사진/동영상 (선택)
-
작업한 내용
- 
PR 포인트
-
> #312 [fix] 추천책 없을 때 터지는 버그 수정

- app/src/main/java/com/sopt/peekabookaos/presentation/recommend/RecommendViewModel.kt
관련 이슈
- closed #311
작업 사진/동영상 (선택)
-
작업한 내용
- 
PR 포인트
-
> #311 [fix] 추천책 수정모드 초기화 로직 추가

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/sopt/peekabookaos/PeekaMessageService.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/main/MainActivity.kt
관련 이슈
- closed #316
작업 사진/동영상 (선택)
-
작업한 내용
- 
PR 포인트
-
> #316 [feat] 안드로이드 13 이상 버전에서 알림 권한 요청하는 로직 구현

- app/src/main/java/com/sopt/peekabookaos/presentation/myPage/MyPageFragment.kt
- app/src/main/res/layout/fragment_my_page.xml
- app/src/main/res/values/strings.xml
관련 이슈
- closed #318
작업 사진/동영상 (선택)
-
작업한 내용
- 
PR 포인트
-
> #318 [feat]  마이페이지 알림 설정창으로 보내는 로직 구현

- app/build.gradle
작업한 내용
- 
1. Base url 수정
2. 버전코드/버전명 수정
> build: upgrade version code and name

- .github/workflows/delivery.yml
- .github/workflows/pr_checker.yml
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationActivity.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationAdapter.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationBookshelfFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationRecommendedFragment.kt
- app/src/main/res/layout/fragment_notification.xml
- app/src/main/res/layout/fragment_notification_bookshelf.xml
- app/src/main/res/layout/fragment_notification_recommended.xml
- app/src/main/res/layout/item_notification.xml
- app/src/main/res/navigation/nav_notification.xml
- app/src/main/res/values/strings.xml
관련 이슈
- closed #322
작업 사진/동영상 (선택)
- x
작업한 내용
- 알림창 네비게이션 구현
PR 포인트
- 알림창 네비게이션 구현
> #322 [feat] 알림창 네비게이션 구현

- app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationAdapter.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationFragment.kt
- app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationRecommendedFragment.kt
- app/src/main/res/layout/fragment_notification_recommended.xml
관련 이슈
- closed #323
작업 사진/동영상 (선택)
-
작업한 내용
- 
PR 포인트
-
> #323 [feat] 알림창에서 들어온 추천받은 책 로직 구현

- app/src/main/java/com/sopt/peekabookaos/presentation/notificationBookshelf/NotificationBookShelfViewModel.kt
관련 이슈
- closed #332
작업 사진/동영상 (선택)
-
작업한 내용
- 
PR 포인트
-
> #332 [fix] 알림에서 친구 책장 진입 시 friendId 0 으로 api 호출되는 버그 수정

- app/src/main/java/com/sopt/peekabookaos/presentation/notification/NotificationAdapter.kt
관련 이슈
- closed #331
작업 사진/동영상 (선택)
-
작업한 내용
- 
PR 포인트
-
> #331 [fix] 알림 typeId 4인 경우 뷰 안 뜨는 버그 수정
